name: whatsapp
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev for now

# App version
version: 1.0.0+1

environment:
  sdk: ^3.8.0-262.0.dev

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ">=5.9.0 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ">=9.1.1 <10.0.0"
  flutter_screenutil: ^5.9.3

  # ---------- UI ----------
  google_fonts: ^6.3.2
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1

  # ---------- Networking ----------
  pretty_dio_logger: ">=1.4.0 <2.0.0"
  connectivity_plus: ">=7.0.0 <8.0.0"
  url_launcher: ">=6.3.2 <7.0.0"

  # ---------- State Management ----------
  get_it: ">=8.2.0 <9.0.0"

  # ---------- Storage ----------
  shared_preferences: ">=2.5.3 <3.0.0"
  flutter_secure_storage: ">=9.2.4 <10.0.0"
  get_storage: ">=2.1.1 <3.0.0"
  go_router: ^16.3.0
  image_picker: ^1.2.0
  logger: ^2.6.1
  equatable: ^2.0.7
  google_maps_flutter: ^2.5.3
  google_maps_flutter_platform_interface: ^2.4.0
  location: ^5.0.0
  geolocator: ^10.1.0
  google_places_flutter: ^2.1.1
  supabase: ^2.10.0
  supabase_flutter: ^2.10.3

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

# fonts:
#   - family: Cairo
#     fonts:
#       - asset: assets/fonts/Cairo-Regular.ttf
#       - asset: assets/fonts/Cairo-Bold.ttf
#         weight: 700

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/assets/
  filename: app_assets.dart
  ignore_comments: true
  classname: AppAssets
  field_prefix: null

dependency_overrides:
  flutter_plugin_android_lifecycle:
    path: ./external/flutter_plugin_android_lifecycle-2.0.31
  location:
    path: ./external/location-5.0.3


