name: whatsapp
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev for now

# App version
version: 1.0.0+1

environment:
  sdk: ^3.8.0-262.0.dev

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ">=5.9.0 <6.0.0"
  flutter:
    sdk: flutter
  flutter_bloc: ">=9.1.1 <10.0.0"
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ">=9.2.4 <10.0.0"
  get_it: ">=8.2.0 <9.0.0"
  get_storage: ">=2.1.1 <3.0.0"
  go_router: ^16.2.4
  google_fonts: ^6.3.2
  image_picker: ^1.2.0
  logger: ^2.6.1
  pretty_dio_logger: ">=1.4.0 <2.0.0"
  skeletonizer: ^2.1.0+1
  url_launcher: ">=6.3.2 <7.0.0"

dev_dependencies:

  # ---------- Code Generation ----------
  build_runner: ^2.4.0

  # ---------- Code Quality ----------
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# ---------- Flutter Settings ----------
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
# ---------- Flutter Assets Generator ----------
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/assets/
  filename: app_assets.dart
  ignore_comments: true
  classname: AppAssets
  field_prefix: null
