name: whatsapp
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev for now

# App version
version: 1.0.0+1

environment:
  sdk: ">=3.8.0-262.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.2
  font_awesome_flutter: 10.9.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ">=5.9.0 <6.0.0"
  equatable: ^2.0.7
  flutter_bloc: ">=9.1.1 <10.0.0"
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ">=9.2.4 <10.0.0"
  flutter_svg: ^2.2.2
  geolocator: ^10.1.0
  get_it: ">=8.2.0 <9.0.0"
  get_storage: ">=2.1.1 <3.0.0"
  go_router: ^16.3.0
  google_fonts: ^6.3.2
  google_maps_flutter: ^2.5.3
  google_maps_flutter_platform_interface: ^2.4.0
  google_places_flutter: ^2.1.1
  http: ^1.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.2.0
  location: ^5.0.0
  logger: ^2.6.1
  pretty_dio_logger: ">=1.4.0 <2.0.0"
  shared_preferences: ">=2.5.3 <3.0.0"
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  supabase_flutter: ^2.10.3
  url_launcher: ">=6.3.2 <7.0.0"
  liquid_glass_renderer: ^0.1.0
  intl: ^0.20.2
  flutter_local_notifications: ^19.5.0
  rxdart: ^0.28.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/assets/
  filename: app_assets.dart
  ignore_comments: true
  classname: AppAssets
  field_prefix: null
