name: whatsapp
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev for now

# App version
version: 1.0.0+1

environment:
  sdk: ^3.8.0-262.0.dev

dependencies:
  flutter:
    sdk: flutter

  # ---------- UI ----------
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1

  # ---------- Networking ----------
  dio: ">=5.9.0 <6.0.0"
  pretty_dio_logger: ">=1.4.0 <2.0.0"
  connectivity_plus: ">=7.0.0 <8.0.0"
  url_launcher: ">=6.3.2 <7.0.0"

  # ---------- State Management ----------
  flutter_bloc: ">=9.1.1 <10.0.0"
  get_it: ">=8.2.0 <9.0.0"

  # ---------- Storage ----------
  shared_preferences: ">=2.5.3 <3.0.0"
  flutter_secure_storage: ">=9.2.4 <10.0.0"
  get_storage: ">=2.1.1 <3.0.0"

  # ---------- Utils ----------
  dartz: ^0.10.1
  logger: ^2.6.1
  intl_phone_field: ^3.2.0
  equatable: ^2.0.5
  go_router: ^16.2.4
  salomon_bottom_bar: ^3.3.2
  google_nav_bar: ^5.0.7
  motion_tab_bar_v2: ^0.4.0
  glassmorphism: ^3.0.0
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # ---------- Code Quality ----------
  flutter_lints: ^5.0.0

  # ---------- Code Generation ----------
  build_runner: ^2.4.0
  json_serializable: ^6.7.0

# ---------- Flutter Settings ----------
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/images/
    - assets/icons/
    - assets/pdf/

  # fonts:
  #   - family: Cairo
  #     fonts:
  #       - asset: assets/fonts/Cairo-Regular.ttf
  #       - asset: assets/fonts/Cairo-Bold.ttf
  #         weight: 700
# ---------- Flutter Assets Generator ----------
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils/assets/
  filename: app_assets.dart
  ignore_comments: true
  classname: AppAssets
  field_prefix: null
